### ISSUE TITLE
Feature 1: User Can Search For Books Or Author 

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/bookopedia#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for books or author.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a page with a search bar where user can type in keywords to search for books that match the keywords.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="382" alt="Issue 1 desktop wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134091764-d03697cf-7cd3-4606-9994-6a8dd4c09604.png">
<img width="179" alt="Issue 1 mobile wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134091767-1b8fb7c7-a3ec-49d0-94f0-106f3e2a8d2f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML & CSS elements.
- [x] Add a `div[data-view="search-form"]` to the HTML.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make input on search bar `required`.
- [x] Concatenate the GET request URL with the search keywords.
- [x] Verify that the response is getting accurate results.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
