### ISSUE TITLE
Feature 2: User Can View List Of Search Results

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/bookopedia#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the list of search results

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user searches for a book or author, a list of the search results will populate.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="383" alt="Issue 2 desktop wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134092543-ca263cdc-4b6e-4580-82a6-66c2ce3449da.png">
<img width="179" alt="Issue 2 mobile wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134092545-15bb7360-f836-4d2f-a5b4-1c80d93ecb64.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="search-results"]`.
- [x] Add an empty unordered list to the `div[data-view="search-results"]` element in the HTML.
- [x] Add some dummy search results to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the results list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single `result` object and returns a DOM tree that matches one of the example results in the HTML.
- [x] Use a loop to create a DOM tree for each search result in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML result once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar to go back to Search Page.
- [x] Ensure that the search function still works.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
