### ISSUE TITLE
Feature 3: User Can View The Details Of A Book

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/bookopedia#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a book

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once a list is populated from the search, the user can click on the "Details" button to get the details of the selected book.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="413" alt="Issue 3 desktop wirefram screenshot" src="https://user-images.githubusercontent.com/87685216/134092793-268b928b-07c0-4bae-ab9c-1c35d9e9f094.png">
<img width="178" alt="Issue 3 mobile wirefram screenshot" src="https://user-images.githubusercontent.com/87685216/134092794-8385ab48-83bc-40e2-83c1-53d2ad0ce328.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create detail view in HTML & CSS
- [x] Add `div[data-view="detail-page"]` to the HTML
- [x] Ensure that each rendered result is given a `data-result-id` attribute indicating which result it is.
- [x] Listen for clicks on the parent element of all rendered result.
- [x] Show the detail page if a detail button was clicked.
- [x] Find the matching results object in the data model and assign it to the data model's `detail` property if a detail button was clicked.
- [x] Pre-populate the details page with the clicked result's values from the object found in the data model.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
