### ISSUE TITLE
Feature 4: User Can Add Books To Bookmarked List

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/bookopedia#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add books to bookmarks list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add books to bookmarks list. Book will be saved to the bookmarks list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="299" alt="Issue 4 mobile wirefram screenshot" src="https://user-images.githubusercontent.com/87685216/134093080-15d598de-5747-43f5-a3c1-25bf36e7eed5.png">
<img width="650" alt="Issue 4 desktop wirefram screenshot" src="https://user-images.githubusercontent.com/87685216/134093082-e6c860bc-179c-4a37-89b2-26c2b2ad9fb5.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the bookmark icon.
- [x] Create a modal that will show when bookmarks are added.
- [x] Add buttons to exit out of the modal or to go to bookmarks.
- [x] When the "+" or 'Add to bookmarks' button is clicked, show modal and add the result to the data model.
- [x] Change the "+" to "-" if book is bookmarked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
