### ISSUE TITLE
Feature 5: User Can View Bookmarked List

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/bookopedia#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view bookmarked list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view bookmarked list by clicking on "Go to Bookmarks" or by clicking on the book icon in the navigation bar. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="320" alt="Issue 5 desktop wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134093397-15e80963-232f-4cd5-868d-eb6d55ddd1e0.png">
<img width="146" alt="Issue 5 mobile wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134093399-24ca2dd2-8c3a-47f8-a819-4bdac703b7bc.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listener to the bookmark icon button in the navigation bar.
- [x] Add event listener to the 'Go to Bookmarks' button in the modal.
- [x] View swap to the result list page when either buttons are clicked.
- [x] Change the header of the page to say "Bookmarks".
- [x] Remove all rendered results.
- [x] Render the results from the bookmarks array in the data model.
- [x] Update the header when the search button in the navigation bar is clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
