### ISSUE TITLE
Feature 6: User Can Remove Books from Bookmarked List

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/bookopedia#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove books from bookmarked list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a book is bookmarked, user can remove it from the bookmarked list by clicking on the '-' button on the top right of the container of the book or by clicking "Remove from Bookmarks" button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="683" alt="Issue 6 desktop wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134093702-4b88b0ab-323c-4d24-935f-daa014cd26f0.png">
<img width="473" alt="Issue 6 mobile wireframe screenshot" src="https://user-images.githubusercontent.com/87685216/134093703-dc229828-4da6-4cc9-a48b-ba9c0abb22b2.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listener for the '-' button on the cards.
- [x] Update the button in the details page to read "Remove from bookmarks" if item is in the data model bookmarks list.
- [x] Add event listener to the "Remove from bookmarks" button in the details page.
- [x] Remove result from the bookmarks in the data model and the rendered list once either button is clicked
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
